version: '2'

services:
  lqs:
    image: hadyelzayady1996/light-app-lqs:latest
    networks:
      - queue-service
      - queue-db
  mongodb:
    image: docker.io/bitnami/mongodb:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGODB_ROOT_PASSWORD: password
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    networks:
      - queue-db

  # mongodb-secondary:
  #   image: docker.io/bitnami/mongodb:7.0
  #   depends_on:
  #     - mongodb-primary
  #   environment:
  #     - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
  #     - MONGODB_REPLICA_SET_MODE=secondary
  #     - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
  #     - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password
  #     - MONGODB_REPLICA_SET_KEY=replicasetkey123

  # mongodb-arbiter:
  #   image: docker.io/bitnami/mongodb:7.0
  #   depends_on:
  #     - mongodb-primary
  #   environment:
  #     - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
  #     - MONGODB_REPLICA_SET_MODE=arbiter
  #     - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
  #     - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
  #     - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
    driver: local

networks:
  queue-service:
    name: queue-service
  queue-db:
